development:
  encoding: unicode
  adapter: postgresql
  database: sampleapp_dev
  username: sue738
  password: sensei1117

test: &test
  encoding: unicode
  adapter: postgresql
  database: sampleapp_test
  username: sue738
  password: sensei1117

production:
  encoding: unicode
  adapter: postgresql
  database: sampleapp_prod
  username: sue738
  password: sensei1117


cucumber:
  <<: *test